import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from '../products.json'
import { description } from 'platform'

export default function Home() {

  console.log("products: ", products)

  return (
    <div className={styles.container}>
      <Head>
        <title>ButcherDox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ButcherDox
        </h1>

        <p className={styles.description}>
          Inspired by the U.S. Supreme Court's recent 
          decision <strong>not</strong> to discourage vigilantism.
          <br/>
          100% of your payment goes toward doxxing and crowd-sourced hunting
          the creature of your choice
        </p>

        <ul className={styles.grid}>
          {products.map( product => {
            const {id, title, description, price, image} = product;
            return (
              <li key={id} className={ styles.card }>
                <a href="https://github.com/vercel/next.js/tree/master/examples">
                  <img src={image} alt={ title }/>
                  <h2>{ title } – ${ price }</h2>
                  <p>{ description }</p>
                </a>
              </li>
            )
          })}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
