import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ButcherDox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ButcherDox
        </h1>

        <p className={styles.description}>
          Inspired by the U.S. Supreme Court's recent 
          decision <strong>not</strong> to discourage vigilantism.
          <br/>
          100% of your payment goes toward doxxing and crowd-sourced hunting
          the creature of your choice
        </p>



        <ul className={styles.grid}>
          <li className={styles.card}>
            <a href="https://github.com/vercel/next.js/tree/master/examples">
              <img src="/images/monkey.jpg" alt="Monkey"/>
              <h2>Monkey</h2>
              <p>Give this wacky chimpanzee the gift of a social panopticon</p>
            </a>
          </li>

          <li className={styles.card}>
            <a href="https://nextjs.org/learn">
            <img src="/images/squirrel.jpg" alt="Squirrel"/>
              <h2>Squirrel</h2>
              <p>Ready to see this cool squirrel's address get leaked on Twitter?</p>
            </a>
          </li>

          <li className={styles.card}>
            <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"> 
              <img src="/images/honeybee.jpg" alt="honeybee"/>
              <h2>Honeybee</h2>
              <p>Protect this bee from the erosive effects of privacy and autonomy</p>
            </a>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
